USE DATABASE HOTEL_DWH;

CREATE OR REPLACE FILE FORMAT FF_CSV TYPE = CSV

FIELD_DELIMITER = ','

SKIP_HEADER =1

FIELD_OPTIONALLY_ENCLOSED_BY='"'

EMPTY_FIELD_AS_NULL=TRUE

NULL_IF=('NULL','','null');